### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by tjschuck** [pfiller/areweatwarwitheastasia#1]
http://areweatwarwitheastasia.com is broken.  I really, really want it fixed.

**Comment by tjschuck** [comment]
:heart: :heart: :heart_eyes_cat: :heart:

**Comment by tjschuck** [comment]
@pfiller I AM NOW PINGING YOU.

![](http://media.giphy.com/media/hzs4g1x7g8iWc/giphy.gif)

**Comment by pfiller** [comment]
Seems to be working now. CAN YOU CONFIRM?

**Comment by tjschuck** [comment]
Is AreWeAtWarWithEastAsia.com working?

**AreWeAtWarWithEastAsia.com has always been working.**
